# Example wrangler.toml (replace account_id, bucket name, and routes as needed)
name = "srp-worker"
main = "worker.js"
compatibility_date = "2024-09-01"

[[r2_buckets]]
binding = "DATA_BUCKET"          # must match env.DATA_BUCKET in code
bucket_name = "chem112-resutls"     # your R2 bucket name

routes = [
  { pattern = "queenschem112srp.com/api/ingest", zone_name = "queenschem112srp.com" },
  { pattern = "queenschem112srp.com/api/ingest/*", zone_name = "queenschem112srp.com" }
]
